version: '3'
services:
  get_new_data:
    image: get_new_data
    container_name: get_new_data-20210120124253
    networks:
    - network-workflow3
    depends_on:
    - tracker-workflow3
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow3:8003
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/examples/demo2/data-eng/:/app
    - /gpfs/bsc_home/xpliu/scanflow/examples/demo2/data-eng/ad-stuff/ad-tracker/tracker-workflow3:/mlflow
  preprocessing_new_data:
    image: preprocessing_new_data
    container_name: preprocessing_new_data-20210120124253
    networks:
    - network-workflow3
    depends_on:
    - tracker-workflow3
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow3:8003
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/examples/demo2/data-eng/:/app
    - /gpfs/bsc_home/xpliu/scanflow/examples/demo2/data-eng/ad-stuff/ad-tracker/tracker-workflow3:/mlflow
  tracker-workflow3:
    image: tracker-workflow3
    container_name: tracker-workflow3-20210120124253
    networks:
    - network-workflow3
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/examples/demo2/data-eng/ad-stuff/ad-tracker/tracker-workflow3:/mlflow
    ports:
    - 8008:8003
networks:
  network_workflow3: null
