apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeling
  name: modeling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modeling
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeling
    spec:
      containers:
#      - env:
#        - name: MLFLOW_TRACKING_URI
#          value: http://tracker-workflow1:8001
      - image: 172.30.0.49:5000/modeling
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        name: modeling
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: modeling-hostpath0
        - mountPath: /mlflow
          name: modeling-hostpath1
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/
        name: modeling-hostpath0
      - hostPath:
          path: /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1
        name: modeling-hostpath1
status: {}
