apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preprocessing
  name: preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
#      - env:
#        - name: MLFLOW_TRACKING_URI
#          value: http://tracker-workflow1:8001
      - image: 172.30.0.49:5000/preprocessing
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        name: preprocessing
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: preprocessing-hostpath0
        - mountPath: /mlflow
          name: preprocessing-hostpath1
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/
        name: preprocessing-hostpath0
      - hostPath:
          path: /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1
        name: preprocessing-hostpath1
status: {}
