apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracker-workflow1
  name: tracker-workflow1
spec:
  type: NodePort
  ports:
  - nodePort: 30010
    port: 8001
    targetPort: 8006
  selector:
    app: tracker-workflow1
