apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-workflow
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science"
