version: '3'
services:
  gathering:
    image: gathering
    container_name: gathering-20210112111721
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/:/app
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    tty: 'true'
  preprocessing:
    image: preprocessing
    container_name: preprocessing-20210112111721
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/:/app
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    tty: 'true'
  modeling:
    image: modeling
    container_name: modeling-20210112111721
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/:/app
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    tty: 'true'
  tracker-workflow1:
    image: tracker-workflow1
    container_name: tracker-workflow1-20210112111721
    networks:
    - network-workflow1
    volumes:
    - /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    ports:
    - 8006:8001
networks:
  network_workflow1: null
