apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preprocessing
  name: preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      volumes:
        - name: pv-workflow
          persistentVolumeClaim:
            claimName: pvc-workflow
        - name: pv-tracker
          persistentVolumeClaim:
            claimName: pvc-tracker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - antiaffinity-pod
            topologyKey: kubernetes.io/hostname
      containers:
#      - env:
#        - name: MLFLOW_TRACKING_URI
#          value: http://tracker-workflow1:8001
      - image: 172.30.0.49:5000/preprocessing
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        name: preprocessing
        resources:
           requests:
             memory: "128Mi"
             cpu: "1"
           limits:
             memory: "128Mi"
             cpu: "1"
        volumeMounts:
        - mountPath: /app
          name: pv-workflow
        - mountPath: /mlflow
          name: pv-tracker
      restartPolicy: Always
status: {}
