apiVersion: v1
kind: Pod
metadata:
  name: gathering
  labels:
    app: gathering
spec:
  volumes:
    - name: pv-workflow
      persistentVolumeClaim:
        claimName: pvc-workflow
    - name: pv-tracker
      persistentVolumeClaim:
        claimName: pvc-tracker
  containers:
    - name: gathering
      image: 172.30.0.49:5000/gathering
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /app
          name: pv-workflow
        - mountPath: /mlflow
          name: pv-tracker
