apiVersion: batch/v1
kind: Job
metadata:
  name: gathering
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      volumes:
        - name: pv-workflow
          persistentVolumeClaim:
            claimName: pvc-workflow
        - name: pv-tracker
          persistentVolumeClaim:
            claimName: pvc-tracker
      containers:
      - name: gathering
        image: 172.30.0.49:5000/gathering 
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://10.244.5.21:8001
        volumeMounts:
          - mountPath: /app
            name: pv-workflow
          - mountPath: /mlflow
            name: pv-tracker
      restartPolicy: Never

