apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeling
  name: modeling
spec:
  type: NodePort
  ports:
  - nodePort: 30011
    port: 8001
    targetPort: 8001
  selector:
    app: modeling
