apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeling
  name: modeling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modeling
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeling
    spec:
      containers:
      - env:
        - name: MLFLOW_TRACKING_URI
          value: http://10.244.5.21:8001
        image: 172.30.0.49:5000/modeling
        imagePullPolicy: IfNotPresent
        name: modeling-20201211152421
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: modeling-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /gpfs/bsc_home/xpliu/scanflow/kubernetes/demo3/data-science/
        name: modeling-hostpath0
status: {}
