apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracker-workflow2
  name: tracker-workflow2
spec:
  type: NodePort
  ports:
  - nodePort: 30011
    port: 8001
    targetPort: 8006
  selector:
    app: tracker-workflow2
